title: Preetam Chhimpa
description: Efficient Multimodal Learning Â· VLM Robustness
theme: minima

# Optional but nice:
minima:
  skin: classic

# This helps GitHub Pages build reliably
plugins:
  - jekyll-feed
